language: go

go:
  - "1.10"

before_install:
  - sudo apt-get install snapd -y
  - sudo snap install hugo
  - sudo snap refresh

install:
  - hugo -t hugo-future-imperfect

deploy:
  target_branch: master
  local_dir: ./public
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source